uptrace:
  replicaCount: 1

  config:
    service:
      env: hosted
      secret: 'FIXME'

    site:
      url: 'http://uptrace.local'

    ch_cluster:
      shards:
        - replicas:
            - addr: ${CH_DATABASE:clickhouse-uptrace1:9000}
              database: ${CH_DATABASE:uptrace}
              user: ${CH_USER:uptrace}
              password: ${CH_USER:uptrace}

    pg:
      addr: ${PG_ADDR:uptrace-postgresql-rw:5432}
      user: ${PG_USER:uptrace}
      password: ${PG_PASSWORD:uptrace}
      database: ${PG_DATABASE:uptrace}

    seed_data:
      users:
        - name: Admin
          key: user1 # Unique user key for links below
          email: admin@uptrace.local
          password: admin
          auth_tokens: ['user1_secret']

      orgs:
        - name: Org1
          key: org1 # Unique org key for links below

      org_users:
        - org: org1 # Link to org key
          user: user1 # Link to user key
          role: owner

      projects:
        - name: Project1
          key: project1 # Unique project key for links below
          org: org1 # Link to org key
          tokens: [project1_secret]

      project_users:
        - project: project1 # Link to project key
          user: user1 # Link to user key
          perm_level: admin

    mailer:
      smtp:
        # Whether to use this mailer for sending emails.
        enabled: false
        # SMTP server host.
        host: localhost
        # SMTP server port.
        port: 1025
        # Username for authentication.
        username: mailhog
        # Password for authentication.
        password: mailhog
        # Uncomment to disable opportunistic TLS.
        #tls: { disabled: true }
        # Emails will be send from this address.
        from: 'uptrace@uptrace.local'

    license:
      data: ''
      # path: /path/to/uptrace/license
