uptrace:
  replicaCount: 1

  config:
    service:
      env: hosted
      secret: 'FIXME'

    site:
      url: http://uptrace.local

    ch_cluster:
      shards:
        - replicas:
            - addr: ${CH_DATABASE:clickhouse-uptrace1:9000}
              database: ${CH_DATABASE:uptrace}
              user: ${CH_USER:uptrace}
              password: ${CH_USER:uptrace}

    pg:
      addr: ${PG_ADDR:uptrace-postgresql-rw:5432}
      user: ${PG_USER:uptrace}
      password: ${PG_PASSWORD:uptrace}
      database: ${PG_DATABASE:uptrace}

    seed_data:
      # Default users created on first startup
      users:
        - key: user1                 # Internal reference key (used in relationships below)
          name: Admin                # Display name in UI
          email: admin@uptrace.local # Login email (must be unique)
          password: admin            # Plain text password (CHANGE THIS IMMEDIATELY!)
          email_confirmed: true

      # API tokens for user authentication
      # These tokens can be used for API access and programmatic operations
      user_tokens:
        - key: user_token1           # Internal reference key
          user_key: user1            # References user.key above
          token: user1_secret        # API token value (CHANGE THIS!)

      # Organizations for multi-tenant deployments
      # Organizations group users and projects together
      orgs:
        - key: org1                  # Internal reference key
          name: Org1                 # Organization display name

      # Organization membership and roles
      # Defines which users belong to which organizations
      org_users:
        - key: org_user1             # Internal reference key
          org_key: org1              # References org.key above
          user_key: user1            # References user.key above
          role: owner                # Role: owner, admin, or member

      # Projects contain telemetry data and are isolated from each other
      # Each project has its own spans, logs, metrics, and dashboards
      projects:
        - key: project1              # Internal reference key
          name: Project1             # Project display name
          org_key: org1              # References org.key above

      # Project-specific tokens for telemetry data ingestion
      # These tokens are used in OTLP DSN strings for sending data
      project_tokens:
        - key: project_token1        # Internal reference key
          project_key: project1      # References project.key above
          token: project1_secret     # Token value for DSN (CHANGE THIS!)

      # Project user permissions
      # Controls who can access and modify project data
      project_users:
        - key: project_user1         # Internal reference key
          project_key: project1      # References project.key above
          org_user_key: org_user1    # References org_user.key above
          perm_level: admin          # Permission level: admin, editor, or viewer

    mailer:
      smtp:
        # Whether to use this mailer for sending emails.
        enabled: false
        # SMTP server host.
        host: localhost
        # SMTP server port.
        port: 1025
        # Username for authentication.
        username: mailhog
        # Password for authentication.
        password: mailhog
        # Uncomment to disable opportunistic TLS.
        #tls: { disabled: true }
        # Emails will be send from this address.
        from: 'uptrace@uptrace.local'

    license:
      data: ''
      # path: /path/to/uptrace/license
