{{- if and .Values.redis.enabled .Values.redis.password }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "uptrace.fullname" . }}-redis
  labels:
    app.kubernetes.io/component: redis
    {{- include "uptrace.labels" . | nindent 4 }}

type: Opaque
data:
  redis-password: {{ .Values.redis.password | b64enc | quote }}
{{- end }}
