{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service

metadata:
  name: {{ include "uptrace.fullname" . }}-redis
  labels:
    app.kubernetes.io/component: redis
    {{- include "uptrace.labels" . | nindent 4 }}

spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/component: redis
    {{- include "uptrace.selectorLabels" . | nindent 4 }}
{{- end }}
