{{- if eq .Values.uptrace.mode "deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptrace.fullname" . }}
  labels:
    app: uptrace
    {{- include "uptrace.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.uptrace.replicaCount }}
  selector:
    matchLabels:
      app: uptrace
      {{- include "uptrace.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.uptrace.config | toYaml | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app: uptrace
        {{- include "uptrace.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "uptrace.pod" . | nindent 6 }}
{{- end }}